version = 0.1

[default.deploy.parameters]
stack_name = "serverless-app"
resolve_s3 = true
s3_prefix = "serverless-app"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
image_repositories = []
